name: Replace URLs in Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  replace-urls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Save comment in file
        run: |
          echo "${{ github.event.comment.body }}" > comment-body.md
      - name: Manipulate comment file
        env:
          COMMENT_UPDATE: false
        run: |
          # Define old & new URLs
          pattern="https://play.google.com/apps/publish?account=8008695526664634386#ReviewDetailsPlace:p=de.danoeh.antennapod&reviewid="
          replacement="https://play.google.com/console/u/0/developers/8008695526664634386/app/4974638472012894302/user-feedback/review-details?reviewId="

          if grep -q "${pattern}" "comment-body.md"; then
              echo "Pattern URL found. Updating comment."
              echo "COMMENT_UPDATE=true" >> $GITHUB_ENV
              sed -i "s!$pattern!$replacement!g" "comment-body.md"
          else
             echo "No action needed."
             exit 0
          fi
      - name: Upload manipulated comment
        if: ${{ env.COMMENT_UPDATE == 'true' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          edit-mode: replace
          body-path: 'comment-body.md'
          token: ${{ secrets.GITHUB_TOKEN }}
