name: Replace URLs in Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  replace-urls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up comment file
        id: setup-comment-file
        run: |
          echo "${{ github.event.comment.body }}" > comment-body.md
      - name: Manipulate comment body
        id: manipulate-comment
        env:
          COMMENT_UPDATE: false  # Initialize URL_MATCH environment variable
        run: |
          # Define the regular expression to capture the old URL
          pattern='https:\/\/play\.google\.com\/apps\/publish\?account=8008695526664634386#ReviewDetailsPlace:p=de\.danoeh\.antennapod&reviewid='

          # Define the new URL
          replacement="https://play.google.com/console/u/0/developers/8008695526664634386/app/4974638472012894302/user-feedback/review-details?reviewId="

          if sed -n "|$pattern|p" "comment-body.md"; then

              # Set COMMENT_UPDATE to true if a match is found and manipulated & store as environment variable
              COMMENT_UPDATE=true
              echo "COMMENT_UPDATE=$COMMENT_UPDATE" >> $GITHUB_ENV

              # Replace URL occurrences
              sed -i "s|$pattern|$replacement|g" "comment-body.md"
          fi

      - name: Update comment if URL match found
        if: ${{ env.COMMENT_UPDATE == 'true' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          edit-mode: replace
          body-path: 'manipulated_body.md'
          token: ${{ secrets.GITHUB_TOKEN }}
